Check Hibernate is present before loading Hazelcast CacheEntryImpl
We have to do it, because when Hibernate CacheEntry
is *not* available then loading Hazelcast CacheEntryImpl
throws NoClassDefFoundError.

This makes some application containers (Wildfly) to freak
out and log scary warnings. They look like this:
```
2021-08-02 11:38:11,540 WARN  [org.jboss.modules.define] (default task-1) Failed to define class com.hazelcast.hibernate.serialization.CacheEntryImpl in Module "deployment.examples.war" from Service Module Loader: java.lang.NoClassDefFoundError: Failed to link com/hazelcast/hibernate/serialization/CacheEntryImpl (Module "deployment.examples.war" from Service Module Loader): org/hibernate/cache/spi/entry/CacheEntry
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1096)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:424)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:555)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
	at org.jboss.modules.Module.loadModuleClass(Module.java:731)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at deployment.examples.war//com.hazelcast.hibernate.serialization.Hibernate5CacheEntrySerializerHook.tryLoadCacheEntryImpl(Hibernate5CacheEntrySerializerHook.java:34)
	at deployment.examples.war//com.hazelcast.hibernate.serialization.Hibernate5CacheEntrySerializerHook.<init>(Hibernate5CacheEntrySerializerHook.java:30)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at deployment.examples.war//com.hazelcast.internal.util.ServiceLoader$NewInstanceIterator.next(ServiceLoader.java:297)
	at deployment.examples.war//com.hazelcast.internal.serialization.impl.SerializerHookLoader.load(SerializerHookLoader.java:62)
	at deployment.examples.war//com.hazelcast.internal.serialization.impl.SerializerHookLoader.<init>(SerializerHookLoader.java:55)
	at deployment.examples.war//com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.registerSerializerHooks(DefaultSerializationServiceBuilder.java:315)
	at deployment.examples.war//com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:241)
	at deployment.examples.war//com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceBuilder.build(EnterpriseSerializationServiceBuilder.java:130)
	at deployment.examples.war//com.hazelcast.internal.serialization.impl.EnterpriseSerializationServiceBuilder.build(EnterpriseSerializationServiceBuilder.java:20)
	at deployment.examples.war//com.hazelcast.client.impl.clientside.EnterpriseClientExtension.createSerializationService(EnterpriseClientExtension.java:93)
	at deployment.examples.war//com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.<init>(HazelcastClientInstanceImpl.java:242)
	at deployment.examples.war//com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:458)
	at deployment.examples.war//com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416)
	at deployment.examples.war//com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:136)
	at deployment.examples.war//com.hazelcast.web.HazelcastInstanceLoader.createClient(HazelcastInstanceLoader.java:112)
	at deployment.examples.war//com.hazelcast.web.HazelcastInstanceLoader.loadInstance(HazelcastInstanceLoader.java:53)
	at deployment.examples.war//com.hazelcast.web.ClusteredSessionService.reconnectHZInstance(ClusteredSessionService.java:135)
	at deployment.examples.war//com.hazelcast.web.ClusteredSessionService.ensureInstance(ClusteredSessionService.java:118)
	at deployment.examples.war//com.hazelcast.web.ClusteredSessionService.init(ClusteredSessionService.java:98)
	at deployment.examples.war//com.hazelcast.web.ClusteredSessionService.<init>(ClusteredSessionService.java:87)
	at deployment.examples.war//com.hazelcast.web.WebFilter.init(WebFilter.java:163)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:111)
```
It's just a warning, safe to ignore, but it looks pretty
scary to users.

When Hibernate is NOT available then Class.forName() throws
just ClassNotFoundException which we catch anyway.
The important difference is that ClassNotFoundException is
seen as less severe than NoClassDefFoundError
and JBoss/Wildfly won't bother logging it on its own.